### ISSUE TITLE
UP您好，希望进一步了解您的代码

### ISSUE THREAD

**Issue by TUTUdeHONGSHAOROU** [HuaHenry/C-Compiler#1]
学长你好，我在github上下载了您写的c语言编译器，目前我们也正在做这门课程设计。您上传的代码中似乎缺少了grammer.txt的文件，最好也能够附有用于测试的.c文件，我想仔细学习一下您的代码特别是文法构建以及最终的汇编部分，不知道您是否能够将文法发送给我，十分期待您的回信，深表感谢。

**Comment by HuaHenry** [comment]
`grammer.txt`如下：
[grammer.txt](https://github.com/user-attachments/files/15856660/grammer.txt)
用于测试的C文件暂时不支持在评论里发送，我会更新到仓库目录中
